version: '2'
services:
  update-dns-8999:
    image: registry.cn-hangzhou.aliyuncs.com/yf_girl/update_dns
    restart: always
    ports:
      - "8999:8999"
    environment:
      - API_DOMAIN=yangfan.cloud
      - API_ACCESSKEYID=LTAIvm2CzSHsTooY
      - API_ACCESSKEY_SECRET=ncBQSP51ngU4B124kw7pLVuVotbECw
    volumes:
      - /home/docker/update-dns:/logs/
      - /etc/timezone:/etc/timezone:ro