server:
  port: 8999

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  resources: # 指定静态资源的路径
    static-locations: classpath:/static/,classpath:/templates/
  profiles:
    active: prod

logging:
  path:  /logs/

# docker 常量配置
api:
  domain:  ${API_DOMAIN:yangfan.cloud}
  AccessKeyId: ${API_ACCESSKEYID:LTAIvm2CzSHsTooY}
  AccessKeySecret: ${API_ACCESSKEY_SECRET:ncBQSP51ngU4B124kw7pLVuVotbECw}
