server:
  port: 8999

spring:
  thymeleaf:
    cache: false
  resources: # 指定静态资源的路径
    static-locations: classpath:/static/,classpath:/templates/
  profiles:
    active: prod

logging:
  path:  /logs/

api:
  domain:  ${API_DOMAIN}
  AccessKeyId: ${API_ACCESSKEYID}
  AccessKeySecret: ${API_ACCESSKEY_SECRET}
#  域名前缀
  prefixUrl: ${PREFIX_URL:local}
